# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  release:
    branches:
      - forge-1.7.10
    types:
      - published

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Set up JDK 6
      id: setup_jdk_6
      uses: actions/setup-java@v1
      with:
        java-version: 6
    - name: Set up JDK 8
      id: setup_jdk_8
      uses: actions/setup-java@v1
      with:
        java-version: 8
    - name: Print Java enviromental variables for debugging purposes.
      run: |
        set | grep JAVA
        echo JDK 6 installated path should be ${{ steps.setup_jdk_6.outputs.path }}
    - name: Build with Gradle
      env:
        GITHUB_ACTIONS_JDK_6: ${{ steps.setup_jdk_6.outputs.path }}
        BUILD_RELEASE: ${{ github.event.release.prerelease == false }}
      uses: eskatos/gradle-command-action@v1
      with:
        gradle-version: wrapper
        wrapper-cache-enabled: false
        dependencies-cache-enabled: false
        configuration-cache-enabled: false
        arguments: SetupCIWorkspace build
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: build/libs
